In [1]:
import numpy as np
import pandas as pd
from numpy import *
import math

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
train

one_hot  one_hot.1  one_hot.2  attribute  attribute.1  attribute.2  \
0          0          0          1      15.26        14.84       0.8710   
1          0          0          1      14.88        14.57       0.8811   
2          0          0          1      14.29        14.09       0.9050   
3          0          0          1      13.84        13.94       0.8955   
4          0          0          1      16.14        14.99       0.9034   
..       ...        ...        ...        ...          ...          ...   
175        1          0          0      12.80        13.47       0.8860   
176        1          0          0      12.79        13.53       0.8786   
177        1          0          0      13.37        13.78       0.8849   
178        1          0          0      12.62        13.67       0.8481   
179        1          0          0      12.76        13.38       0.8964   

     attribute.3  attribute.4  attribute.5  attribute.6  
0          5.763        3.312        2.221        5.220  
1          5.554        3.333        1.018        4.956  
2          5.291        3.337        2.699        4.825  
3          5.324        3.379        2.259        4.805  
4          5.658        3.562        1.355        5.175  
..           ...          ...          ...          ...  
175        5.160        3.126        4.873        4.914  
176        5.224        3.054        5.483        4.958  
177        5.320        3.128        4.670        5.091  
178        5.410        2.911        3.306        5.231  
179        5.073        3.155        2.828        4.830  

[180 rows x 10 columns]

In [3]:
stopping_criterion=100
w=np.zeros((3,2))
num_train=train.size/10
num_test = test.size/7
w

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
predict=np.zeros((180,3))
target=np.zeros((180,3))
for i in range (0,180):
    for j in range (0,3):
        target[i][j]=train.iloc[i][j]

In [5]:
def update_predict(predict,w,train):
    for i in range (0,180):
        numerator=np.zeros((1,3))
        for j in range (0,3):
            for k in range (0,2):
                numerator[0][j]=numerator[0][j]+w[j][k]*train.iloc[i][k+3]     
        denominator=0
        for j in range (0,3):
            denominator=denominator+np.exp(numerator[0][j])
        
        for j in range (0,3):
            predict[i][j]=np.exp(numerator[0][j])/denominator
        
    return predict

def Error_f(predict,target):
    error=0
    for i in range (0,180):
        for j in range (0,3):
            error=error+target[i][j]*np.log(predict[i][j])
            
    return -1*error

def d_Error_f(j,predict,target,train_data):
    d_error=np.zeros((1,2))
    basis=np.zeros((1,2))
    for i in range (0,180):
        for k in range (0,2):
            basis[0][k]=train_data.iloc[i][k+3]
            d_error=d_error+ (predict[i][j]-target[i][j] )*basis
    return d_error

def hessian(j,predict,train_data):
    H=np.zeros((2,2))
    basis=np.zeros((1,2))
    for i in range (0,180):
        for k in range (0,2):
            basis[0][k]=train_data.iloc[i][k+3]
        H=H+(predict[i][j])*(1-predict[i][j])*basis.T.dot(basis)
    return H

def cal_train_acc(train,predict):
    predict_class=np.zeros((180,1))
    for i in range(0,180):
        if (predict[i][0]>=predict[i][1]) and ((predict[i][0]>=predict[i][2])):
            predict_class[i][0]=1
        elif (predict[i][1]>=predict[i][0]) and ((predict[i][1]>=predict[i][2])):
            predict_class[i][0]=2
        elif (predict[i][2]>=predict[i][0]) and ((predict[i][2]>=predict[i][1])):
            predict_class[i][0]=3
    correct=0
    for i in range(0,180):
        if (train.loc[i][10]==predict_class[i][0]):
            correct=correct+1
    return correct/180*100

In [6]:
update_predict(predict,w,train)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.

In [7]:
error=10000000000000
iteration=1
while error>100:
    ##w_new0=np.zeros((1,7))
    ##w_new1=np.zeros((1,7))
    ##w_new2=np.zeros((1,7))
    w_old0=w[0][:].copy()
    w_old1=w[1][:].copy()
    w_old2=w[2][:].copy()
    
    w[0][:] = w_old0-d_Error_f(0,predict,target,train).dot( np.linalg.pinv(hessian(0,predict,train).T) )
    w[1][:] = w_old1-d_Error_f(1,predict,target,train).dot( np.linalg.pinv(hessian(1,predict,train).T) )
    w[2][:] = w_old2-d_Error_f(2,predict,target,train).dot( np.linalg.pinv(hessian(2,predict,train).T) )
    
    predict=update_predict(predict,w,train)
    error=Error_f(predict,target)
    print("iteration:",iteration,"  error:",error)
    iteration=iteration+1
    print(w)
print(error)   

iteration: 1   error: 98.66278829326836
[[-2.0447622   2.09826375]
 [ 2.18185152 -2.23585912]
 [-0.13708931  0.13759537]]
98.66278829326836


In [8]:
predict

array([[3.11353081e-01, 3.72661158e-01, 3.15985760e-01],
       [3.83339960e-01, 2.96712657e-01, 3.19947383e-01],
       [4.53298572e-01, 2.32077149e-01, 3.14624279e-01],
       [6.48865176e-01, 9.50008708e-02, 2.56133953e-01],
       [3.24479987e-02, 8.36044982e-01, 1.31507019e-01],
       [4.76976816e-01, 2.12360908e-01, 3.10662276e-01],
       [4.60841577e-01, 2.26007802e-01, 3.13150621e-01],
       [5.84148664e-01, 1.33826296e-01, 2.82025040e-01],
       [3.14824223e-02, 8.39222605e-01, 1.29294973e-01],
       [2.85837297e-02, 8.48095702e-01, 1.23320568e-01],
       [3.18337948e-01, 3.64860222e-01, 3.16801830e-01],
       [6.69154265e-01, 8.42868030e-02, 2.46558932e-01],
       [6.67076765e-01, 8.52993719e-02, 2.47623863e-01],
       [7.43062361e-01, 5.01866729e-02, 2.06750966e-01],
       [7.56163492e-01, 4.50378762e-02, 1.98798632e-01],
       [3.77916228e-01, 3.01778158e-01, 3.20305613e-01],
       [4.76962422e-01, 2.12054727e-01, 3.10982852e-01],
       [6.83368125e-02, 7.43750

In [9]:

mask1=(train['one_hot']==1)
mask2=(train['one_hot.1']==1)
mask3=(train['one_hot.2']==1)

train.loc[mask1,'class']=1
train.loc[mask2,'class']=2
train.loc[mask3,'class']=3
train

one_hot  one_hot.1  one_hot.2  attribute  attribute.1  attribute.2  \
0          0          0          1      15.26        14.84       0.8710   
1          0          0          1      14.88        14.57       0.8811   
2          0          0          1      14.29        14.09       0.9050   
3          0          0          1      13.84        13.94       0.8955   
4          0          0          1      16.14        14.99       0.9034   
..       ...        ...        ...        ...          ...          ...   
175        1          0          0      12.80        13.47       0.8860   
176        1          0          0      12.79        13.53       0.8786   
177        1          0          0      13.37        13.78       0.8849   
178        1          0          0      12.62        13.67       0.8481   
179        1          0          0      12.76        13.38       0.8964   

     attribute.3  attribute.4  attribute.5  attribute.6  class  
0          5.763        3.312        2.221        5.220    3.0  
1          5.554        3.333        1.018        4.956    3.0  
2          5.291        3.337        2.699        4.825    3.0  
3          5.324        3.379        2.259        4.805    3.0  
4          5.658        3.562        1.355        5.175    3.0  
..           ...          ...          ...          ...    ...  
175        5.160        3.126        4.873        4.914    1.0  
176        5.224        3.054        5.483        4.958    1.0  
177        5.320        3.128        4.670        5.091    1.0  
178        5.410        2.911        3.306        5.231    1.0  
179        5.073        3.155        2.828        4.830    1.0  

[180 rows x 11 columns]

In [10]:
print("acc:",cal_train_acc(train,predict),"%" )

acc: 66.66666666666666 %


In [11]:
print(w)
####################################################################################################
def predict_testdata(predict,w,test):
    for i in range (0,30):
        numerator=np.zeros((1,3))
        for j in range (0,3):
            for k in range (0,2):
                numerator[0][j]=numerator[0][j]+w[j][k]*test.iloc[i][k]

            
        ##print("debug:",numerator)        
        denominator=0
        print()
        for j in range (0,3):
            denominator=denominator+np.exp(numerator[0][j])
        
        for j in range (0,3):
            predict[i][j]=np.exp(numerator[0][j])/denominator
        
    return predict
####################################################################################################


[[-2.0447622   2.09826375]
 [ 2.18185152 -2.23585912]
 [-0.13708931  0.13759537]]


In [12]:
test=pd.read_csv('test.csv')
print(test)
predict_test=np.zeros((30,3))
predict_test=predict_testdata(predict_test,w,test)

    attribute  attribute.1  attribute.2  attribute.3  attribute.4  \
0       12.76        13.38       0.8964        5.073        3.155   
1       11.23        12.63       0.8840        4.902        2.879   
2       12.36        13.19       0.8923        5.076        3.042   
3       13.22        13.84       0.8680        5.395        3.070   
4       12.78        13.57       0.8716        5.262        3.026   
5       12.88        13.50       0.8879        5.139        3.119   
6       14.34        14.37       0.8726        5.630        3.190   
7       14.01        14.29       0.8625        5.609        3.158   
8       14.37        14.39       0.8726        5.569        3.153   
9       12.73        13.75       0.8458        5.412        2.882   
10      18.30        15.89       0.9108        5.979        3.755   
11      18.94        16.32       0.8942        6.144        3.825   
12      15.38        14.90       0.8706        5.884        3.268   
13      16.16        15.33       0

In [13]:
predict_test

array([[8.56119440e-01, 1.47823957e-02, 1.29098165e-01],
       [9.65132775e-01, 6.68423005e-04, 3.41988024e-02],
       [9.01472929e-01, 6.53972401e-03, 9.19873467e-02],
       [8.59404396e-01, 1.41231101e-02, 1.26472494e-01],
       [8.95909998e-01, 7.38843531e-03, 9.67015670e-02],
       [8.56983171e-01, 1.46076341e-02, 1.28409195e-01],
       [6.13912071e-01, 1.15370287e-01, 2.70717641e-01],
       [7.45844763e-01, 4.91442534e-02, 2.05010983e-01],
       [6.08048087e-01, 1.18945458e-01, 2.73006455e-01],
       [9.32835706e-01, 2.85431623e-03, 6.43099774e-02],
       [2.06155639e-04, 9.90980478e-01, 8.81336649e-03],
       [8.91806210e-05, 9.94347889e-01, 5.56293077e-03],
       [2.72715826e-01, 4.17931942e-01, 3.09352232e-01],
       [1.04325495e-01, 6.70142193e-01, 2.25532312e-01],
       [1.65140013e-01, 5.65558453e-01, 2.69301534e-01],
       [1.39811301e-01, 6.06297890e-01, 2.53890809e-01],
       [5.91455435e-03, 9.39787636e-01, 5.42978094e-02],
       [3.16854983e-01, 3.66815

In [14]:
predict_test_class=np.zeros((30,3))
for i in range(30):
    if (predict_test[i][0]>=predict_test[i][1]) and ((predict_test[i][0]>=predict_test[i][2])):
            predict_test_class[i][0]=1
            predict_test_class[i][1]=0
            predict_test_class[i][2]=0
    elif (predict_test[i][1]>=predict_test[i][0]) and ((predict_test[i][1]>=predict_test[i][2])):
            predict_test_class[i][0]=0
            predict_test_class[i][1]=1
            predict_test_class[i][2]=0
    elif (predict_test[i][2]>=predict_test[i][0]) and ((predict_test[i][2]>=predict_test[i][1])):
            predict_test_class[i][0]=0
            predict_test_class[i][1]=0
            predict_test_class[i][2]=1
predict_test_class

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])